trigger:
- master
- refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    node_12_x:
      node_version: 12.x
    node_14_x:
      node_version: 14.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(node_version)'
  displayName: 'Use node.js $(node_version)'

- script: npm i
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build'

# - task: CopyFiles@2
#   inputs:
#     contents: dist/**
#     targetFolder: $(Build.ArtifactStagingDirectory)

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'dist'
#     publishLocation: 'Container'

